### PR TITLE
rwc2022: soundboard in bridge

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
~Not tested yet~, tested

**Review by PetervDooren — CHANGES_REQUESTED** [review]
We ideally do not want to add functionality to hero bridge. 

I think it would be better to move this to a soundboard robot part in robot skills. 

Do you think we should do that now or after the rwc2022 merge?

**Comment by MatthijsBurgh** [comment]
We use the hero_bridge for interfaces that are used both by robot_skills and by other parts of the software stack. It provides interfaces AND functionality that was otherwise provided by our original code and is now missing in the Toyota code.

By moving the functionality to robot_skills, the robot behavior is not consistent. As the functionality is not available when the interface is used by another part of the software stack. So it is not possible to move this functionality.

**Comment by MatthijsBurgh** [comment]
I still need to implement the publishing of the sentence that is being spoken

**Review by PetervDooren — COMMENTED** [review]
I still think we should not add functionality to hero bridge

**Comment by MatthijsBurgh** [comment]
@PetervDooren ideally not. But this shouldn't be in robot skills, as the provided interface is also used outside robot skills.

Consistent behavior is more important, than not having functionality here.

We can build another node, which provides the current interface with the functionality. Which then interfaces with this bridge without this functionality. But i think that is just stupid.

**Review by PetervDooren — APPROVED** [review]

**Comment by PetervDooren** [comment]
Fair point, I dont know the right place for thos functionality but that is no reason to hold this PR.
Hero bridge is the ducttape with which our codebase is stapled to the hsrb. It breaks many interfaces in the process. I hope one day we can get rid of this repo altogether.

**Pull request merged**
